python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
