python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
python main.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 A game unet_onestand_rot90 eva_ckpt None
