python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
@REM 10
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
@REM 10
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
@REM 10
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
@REM 10
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
@REM 10
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
@REM 10
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
@REM 10
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 B None
python ../eva_ckpt.py C:/Users/hayakawa/work/mytensor/dataset2 Z:/hayakawa/binary 0 20 E None
@REM 10
@REM python ../main.py C:\Users\hayakawa\work\mytensor\dataset2 Z:\hayakawa\binary 0 20 E None
@REM python main_nostand.py C:\Users\hayakawa\work\mytensor\dataset2 Y:\hayakawa\binary 0 20 E None
@REM python main_nostand.py C:\Users\hayakawa\work\mytensor\dataset2 Y:\hayakawa\binary 0 20 E None
@REM python check_speed.py unet_1ud unet_0001_sigmoid_detac C:\Users\hayakawa\work\mytensor\dataset2 Y:\hayakawa\binary game2 3
@REM python check_speed.py unet_3ud unet_0001_sigmoid_detac C:\Users\hayakawa\work\mytensor\dataset2 Y:\hayakawa\binary game2 3
